@url = http://localhost:7777
@id = 1

###

GET {{url}}/notes

###

POST {{url}}/notes
Content-Type: application/json

{
    "id": 0,
    "content": "First Note"
}

###

DELETE {{url}}/notes/{{id}}